options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--no-cache', '-t', 'gcr.io/her-feeling/text-moods-api', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/her-feeling/text-moods-api']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'her-feeling-server', '--image', 'gcr.io/her-feeling/text-moods-api', '--region', 'asia-southeast1', '--port', '8080']

images:
  - gcr.io/her-feeling/text-moods-api
