version: "3.8"
services:
  db:
    image: mysql:8.4
    container_name: herfeeling
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=herfeeling
      - TZ=Asia/Bangkok
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
