name: Build image

on:
  push:
    branches:
      - feat/implement-ci

  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Delete Old version of Docker image
        run: |
          echo ${{ secrets.DOCKER_USERNAME }}
          docker rmi ${{ secrets.DOCKER_USERNAME }}/her-feeling-server || echo "Image not found, skipping deletion"
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/her-feeling-server .
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/her-feeling-server
