name: Build image

on:
  push:
    branches:
      - feat/implement-ci

  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Verify Docker login
        run: docker info
      - name: Delete Old version of Docker image
        run: |
          docker rmi migboy03/her-feeling-server || echo "Image not found, skipping deletion"
      - name: Build Docker image
        run: |
          docker build -t migboy03/her-feeling-server .
      - name: Push Docker image
        run: |
          docker push migboy03/her-feeling-server
